#ifndef DEFS_H
#define DEFS_H

// DEFINIÇÃO DE ESTADO INICIAL E QUAL ESTADO GERA ERRO, (NAO FUNCIONOU COM ESTADO DE ERRO -1)
#define INITIAL_STATE 1
#define ERROR_STATE 0

// DEFINES PARA O AUTOMATO, POSSO TER QUE ALTERAR EM CASO DE ERRO NO MEU AUTOMATO
#define N_ESTADOS 174
#define N_ASCII 128


#endif